"""
FRED Series configuration for the US Macro Dashboard.
Defines all indicators, their metadata, categories, and display settings.
"""

FRED_SERIES = {
    # ── 1. GDP & Economic Output ──────────────────────────────────────────────
    "GDPC1": {
        "name": "Real GDP",
        "category": "GDP & Output",
        "description": "Real Gross Domestic Product (inflation-adjusted)",
        "units": "Billions of Chained 2017 Dollars",
        "frequency": "Q",
        "format": ",.0f",
        "prefix": "$",
        "suffix": "B",
        "color": "#2563eb",
    },
    "INDPRO": {
        "name": "Industrial Production Index",
        "category": "GDP & Output",
        "description": "Index of industrial production across manufacturing, mining, utilities",
        "units": "Index 2017=100",
        "frequency": "M",
        "format": ".1f",
        "prefix": "",
        "suffix": "",
        "color": "#1d4ed8",
    },

    # ── 2. Inflation ──────────────────────────────────────────────────────────
    "CPIAUCSL": {
        "name": "CPI (All Items)",
        "category": "Inflation",
        "description": "Consumer Price Index for All Urban Consumers",
        "units": "Index 1982-84=100",
        "frequency": "M",
        "format": ".1f",
        "prefix": "",
        "suffix": "",
        "color": "#dc2626",
    },
    "CPILFESL": {
        "name": "Core CPI",
        "category": "Inflation",
        "description": "CPI excluding food and energy (less volatile)",
        "units": "Index 1982-84=100",
        "frequency": "M",
        "format": ".1f",
        "prefix": "",
        "suffix": "",
        "color": "#b91c1c",
    },
    "PCEPI": {
        "name": "PCE Price Index",
        "category": "Inflation",
        "description": "Personal Consumption Expenditures Price Index (Fed's preferred measure)",
        "units": "Index 2017=100",
        "frequency": "M",
        "format": ".1f",
        "prefix": "",
        "suffix": "",
        "color": "#ef4444",
    },
    "PCEPILFE": {
        "name": "Core PCE",
        "category": "Inflation",
        "description": "PCE excluding food and energy",
        "units": "Index 2017=100",
        "frequency": "M",
        "format": ".1f",
        "prefix": "",
        "suffix": "",
        "color": "#f87171",
    },
    "PPIACO": {
        "name": "Producer Price Index",
        "category": "Inflation",
        "description": "PPI for all commodities — leading indicator of consumer inflation",
        "units": "Index 1982=100",
        "frequency": "M",
        "format": ".1f",
        "prefix": "",
        "suffix": "",
        "color": "#fca5a5",
    },

    # ── 3. Labor Market ───────────────────────────────────────────────────────
    "UNRATE": {
        "name": "Unemployment Rate",
        "category": "Labor Market",
        "description": "Percentage of labor force unemployed but actively seeking work",
        "units": "Percent",
        "frequency": "M",
        "format": ".1f",
        "prefix": "",
        "suffix": "%",
        "color": "#d97706",
    },
    "PAYEMS": {
        "name": "Nonfarm Payrolls",
        "category": "Labor Market",
        "description": "Total nonfarm payroll employment (thousands)",
        "units": "Thousands of Persons",
        "frequency": "M",
        "format": ",.0f",
        "prefix": "",
        "suffix": "K",
        "color": "#b45309",
    },
    "CIVPART": {
        "name": "Labor Force Participation Rate",
        "category": "Labor Market",
        "description": "Percentage of civilian population in the labor force",
        "units": "Percent",
        "frequency": "M",
        "format": ".1f",
        "prefix": "",
        "suffix": "%",
        "color": "#f59e0b",
    },
    "CES0500000003": {
        "name": "Average Hourly Earnings",
        "category": "Labor Market",
        "description": "Average hourly earnings of all private employees",
        "units": "Dollars per Hour",
        "frequency": "M",
        "format": ".2f",
        "prefix": "$",
        "suffix": "/hr",
        "color": "#fbbf24",
    },

    # ── 4. Consumer & Business Sentiment ─────────────────────────────────────
    "UMCSENT": {
        "name": "Consumer Sentiment (UMich)",
        "category": "Sentiment",
        "description": "University of Michigan Consumer Sentiment Index",
        "units": "Index 1966:Q1=100",
        "frequency": "M",
        "format": ".1f",
        "prefix": "",
        "suffix": "",
        "color": "#7c3aed",
    },

    # ── 5. Monetary Policy / Interest Rates ───────────────────────────────────
    "FEDFUNDS": {
        "name": "Federal Funds Rate",
        "category": "Monetary Policy",
        "description": "Effective federal funds rate — primary Fed policy tool",
        "units": "Percent",
        "frequency": "M",
        "format": ".2f",
        "prefix": "",
        "suffix": "%",
        "color": "#059669",
    },
    "GS10": {
        "name": "10-Year Treasury Yield",
        "category": "Monetary Policy",
        "description": "Market Yield on 10-Year U.S. Treasury Securities",
        "units": "Percent",
        "frequency": "M",
        "format": ".2f",
        "prefix": "",
        "suffix": "%",
        "color": "#10b981",
    },
    "T10Y2Y": {
        "name": "Yield Curve (10Y-2Y)",
        "category": "Monetary Policy",
        "description": "Spread between 10-year and 2-year Treasuries — inversion often precedes recession",
        "units": "Percent",
        "frequency": "D",
        "format": ".2f",
        "prefix": "",
        "suffix": "%",
        "color": "#34d399",
    },

    # ── 6. Financial Conditions ────────────────────────────────────────────────
    "SP500": {
        "name": "S&P 500",
        "category": "Financial Conditions",
        "description": "S&P 500 Stock Price Index",
        "units": "Index",
        "frequency": "D",
        "format": ",.0f",
        "prefix": "",
        "suffix": "",
        "color": "#0891b2",
    },
    "BAA10Y": {
        "name": "BAA Corp Bond Spread",
        "category": "Financial Conditions",
        "description": "Moody's BAA Corporate Bond spread over 10-Year Treasury — risk indicator",
        "units": "Percent",
        "frequency": "D",
        "format": ".2f",
        "prefix": "",
        "suffix": "%",
        "color": "#0e7490",
    },
    "TOTALSL": {
        "name": "Total Consumer Credit",
        "category": "Financial Conditions",
        "description": "Total outstanding consumer credit (revolving + non-revolving)",
        "units": "Billions of Dollars",
        "frequency": "M",
        "format": ",.0f",
        "prefix": "$",
        "suffix": "B",
        "color": "#06b6d4",
    },

    # ── 7. International Trade ────────────────────────────────────────────────
    "NETEXP": {
        "name": "Trade Balance",
        "category": "International Trade",
        "description": "Net exports of goods and services",
        "units": "Billions of Dollars",
        "frequency": "Q",
        "format": ",.1f",
        "prefix": "$",
        "suffix": "B",
        "color": "#db2777",
    },
    "EXPGS": {
        "name": "Exports",
        "category": "International Trade",
        "description": "Exports of goods and services",
        "units": "Billions of Dollars",
        "frequency": "Q",
        "format": ",.1f",
        "prefix": "$",
        "suffix": "B",
        "color": "#ec4899",
    },
    "IMPGS": {
        "name": "Imports",
        "category": "International Trade",
        "description": "Imports of goods and services",
        "units": "Billions of Dollars",
        "frequency": "Q",
        "format": ",.1f",
        "prefix": "$",
        "suffix": "B",
        "color": "#f472b6",
    },

    # ── 8. Housing / Real Estate ──────────────────────────────────────────────
    "HOUST": {
        "name": "Housing Starts",
        "category": "Housing",
        "description": "Total housing starts — early indicator of real estate activity",
        "units": "Thousands of Units",
        "frequency": "M",
        "format": ",.0f",
        "prefix": "",
        "suffix": "K",
        "color": "#65a30d",
    },
    "NHSLTOT": {
        "name": "New Home Sales",
        "category": "Housing",
        "description": "New single-family home sales",
        "units": "Thousands of Units",
        "frequency": "M",
        "format": ",.0f",
        "prefix": "",
        "suffix": "K",
        "color": "#4d7c0f",
    },
    "CSUSHPINSA": {
        "name": "Case-Shiller Home Price Index",
        "category": "Housing",
        "description": "S&P/Case-Shiller U.S. National Home Price Index",
        "units": "Index Jan 2000=100",
        "frequency": "M",
        "format": ".1f",
        "prefix": "",
        "suffix": "",
        "color": "#84cc16",
    },
}

# Categories in display order
CATEGORIES = [
    "GDP & Output",
    "Inflation",
    "Labor Market",
    "Sentiment",
    "Monetary Policy",
    "Financial Conditions",
    "International Trade",
    "Housing",
]

# Series grouped by category
SERIES_BY_CATEGORY = {}
for series_id, meta in FRED_SERIES.items():
    cat = meta["category"]
    SERIES_BY_CATEGORY.setdefault(cat, []).append({"id": series_id, **meta})
